### ISSUE TITLE
Creating New Use Cases

### ISSUE THREAD

**Issue by konakion** [Sensors-in-Paradise/android-native-xsens#206]
## Description

Creating new use cases is not intuitive. The plus button doesn't work as assumed (including subdirectories). Creating new use cases works only if the title is set.

**Comment by lucasliebe** [comment]
First of all this is not a bug but planned behavior since renaming UseCases after their creation is out of scope for this project because of time constraints. It is intuitive since you get visual feedback. A normal user should be able to assume and understand this behavior easily.
Considering the mentioned points this will not be worked on and the issue will be closed.
